In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

from collections import defaultdict
from pathlib import Path
import pandas as pd

Mounted at /content/gdrive

In [ ]:
!cp gdrive/MyDrive/LAB1_TMS/extras/preprocessing_functions.py preprocessing_functions.py
!cp gdrive/MyDrive/LAB1_TMS/extras/corpus.zip corpus.zip

# Loading the data

In [ ]:
import nltk
from preprocessing_functions import load_president_speeches, remove_punctuation, remove_numbers
data = load_president_speeches()
data.head(2)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

   year   president                                               text
0  1957  Eisenhower  The Price of Peace\nMr. Chairman, Mr. Vice Pre...
1  1969       Nixon  Senator Dirksen, Mr. Chief Justice, Mr. Vice P...

In [ ]:
#Pre-process
data["preprocessed"] = data.text.str.lower()
data.preprocessed = data.preprocessed.apply(remove_numbers)
data.preprocessed =  data.preprocessed.apply(remove_punctuation)
data["tokens"] = data.preprocessed.str.split()
data.head(3)
print(len(data))

56

In [ ]:
data.head(2)

,year,president,text,preprocessed,tokens
0,1973,Nixon,"Mr. Vice President, Mr. Speaker, Mr. Chief Jus...",mr vice president mr speaker mr chief jus...,"[mr, vice, president, mr, speaker, mr, chief, ..."
1,1833,Jackson,"Fellow citizens, the will of the American peop...",fellow citizens the will of the american peop...,"[fellow, citizens, the, will, of, the, america..."

# Exercise 0: Simple Document Representation

Given the query: "senator mathias", write code that returns all the documents that contain it. Hints:

1.   Use the preprocessed column of the dataframe and the str.contains function\
TRY: https://www.geeksforgeeks.org/python-pandas-series-str-find/
2.   Create a new column in the dataframe that contains the True or False value.

In [ ]:
# EXERCISE: Your code here
data['search'] = data['preprocessed'].
display(data[data.search])
print(data[data.search].shape)

,year,president,text,preprocessed,tokens,search
18,1985,Reagan,"Senator Mathias, Chief Justice Burger, Vice Pr...",senator mathias chief justice burger vice pr...,"[senator, mathias, chief, justice, burger, vic...",True

(1, 6)

Given the query: "senator mathias", write code that returns all the documents ranked based on the tf-idf similarity. Hints:

1.  Use the tf-idf vectorizer from the sklearn
2.  Fit the documents in the vectorizer
3.  Write a function that takes the document vectors, a query (a text) and the vectorizer and returns the cosine similarity between the 2 vectors.
4.  Display the president and the year of the documents that have similarity with the query > 0.02. The query is: "senator mathias"

In [ ]:
# Your code here

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
docs_tfidf = vectorizer.fit_transform(data.preprocessed)

In [ ]:
def get_tf_idf_query_similarity(vectorizer, docs_tfidf, query):
    query_tfidf = vectorizer.transform([query])
    similarities = cosine_similarity(query_tfidf, docs_tfidf).flatten()
    return similarities

In [ ]:
ex_query = 'senator mathias'
similarities = get_tf_idf_query_similarity(vectorizer, docs_tfidf, ex_query)

display(similarities)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01507705, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01437518, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00910075, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00754142,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05175934, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [ ]:
for doc_sim in similarities:
  # EXERCISE: Display the documents that have similarity with the query > 0.02
  if doc_sim > 0.02:
      display(data[['president', 'year']].iloc[list(similarities).index(doc_sim)])

president    Reagan
year         1985
Name: 38, dtype: object

# Exercise 1: Static Word Embeddings

---

Steps:

Part 1 **Training Word2vec on a dataset**:
- Train a Word2Vec model on the presidents' speeches. You must pass to Word2Vec a list of lists of tokens (a list of tokenized sentences). Use CBOW and a window of 5. Documentation: https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
- Find the words most similar to, e.g. "state", "states", "president", or others.
- Compare the effectiveness of CBOW and Skipgram. Which one works better?


Part 2 **Using pre-trained static models**:
- Load a pre-trained gensim model (available models: https://github.com/RaRe-Technologies/gensim-data#Models) (Choose a small one to avoid waiting for the download, e.g. `glove-wiki-gigaword-100`).
- Evaluate the following relations:
  - king + woman - man = ?
  - France - Paris + London = ?
  - Find out some for yourselves

**Question: Find the words most similar to "italy" using the 2 models (trained and pretrained). What do you observe? Why? Any solution?**

In [ ]:
# Your code here

from gensim import downloader
from gensim.models import Word2Vec

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
data['sent_tokens'] = data.text.str.lower()

data.sent_tokens = data.sent_tokens.str.replace(r'\d+', ' ', regex=True)
data.sent_tokens = data.sent_tokens.apply(lambda input_text : [remove_punctuation(t).split() for t in nltk.sent_tokenize(input_text)])

!

In [ ]:
len(data.sent_tokens.sum())

4854

In [ ]:
len(data.sent_tokens)

56

In [ ]:
corpus = data.sent_tokens.sum() # set a list of sentences rather than list of list of words
# now use the slides code for training!

model = Word2Vec(sentences=corpus, size=100, window=5, sg=1, seed=42)
# use sg=1 for skip-gram and sg=0 for CBoW

# set similar words to:
# states, war, state
print(model.wv.most_similar('states', topn=10))

# try also italy and see what happens!

[('powers', 0.912544310092926), ('defend', 0.8784132599830627), ('united', 0.8738170266151428), ('constitution', 0.8664664626121521), ('protect', 0.8534152507781982), ('federal', 0.8480732440948486), ('reserved', 0.8475136756896973), ('authority', 0.8374835252761841), ('several', 0.8319411277770996), ('laws', 0.8169540762901306)]

In [ ]:
import numpy as np
try:
    italy_vector = model.wv.most_similar('italy', topn=10)
except KeyError as e:
    italy_vector = np.zeros(100)

print(italy_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]

In [ ]:
downloader.info()['models'].keys()

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [ ]:
wiki_model = downloader.load('glove-wiki-gigaword-100')

[==================================================] 100.0% 128.1/128.1MB downloaded

In [ ]:
wiki_model.wv['president']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.

array([-0.064549, -0.13812 ,  0.50017 ,  0.41434 ,  0.45832 , -0.048331,
       -0.21651 ,  0.34987 , -0.83235 , -0.62282 , -0.40099 , -0.31978 ,
        0.42928 , -0.026035, -0.16171 , -0.32513 ,  0.77604 , -0.39852 ,
       -0.67013 , -0.55876 , -0.39863 , -0.28143 ,  0.68614 ,  0.29229 ,
       -0.7146  ,  0.36995 , -0.45309 , -0.23193 ,  0.76916 , -0.031589,
        1.0603  ,  1.5446  , -0.13272 ,  0.33701 , -0.97561 ,  0.73617 ,
        0.60841 ,  0.558   , -0.39274 ,  0.1121  , -1.0474  , -0.03692 ,
        0.99908 , -0.044925, -0.41186 ,  0.19605 ,  0.093281, -0.59623 ,
       -0.60765 , -0.4742  , -0.30162 , -0.70128 , -0.20055 ,  0.99519 ,
        0.20088 , -2.5636  , -0.14627 ,  0.77824 ,  1.4913  ,  0.29724 ,
       -0.12084 , -0.060082,  0.079881, -0.38348 ,  0.41371 , -0.41284 ,
        0.61702 ,  1.1316  , -0.047434,  0.2848  ,  0.57694 , -0.45501 ,
       -0.76359 , -1.1659  ,  0.068946, -0.22498 ,  0.18691 ,  0.64142 ,
       -1.7505  , -0.091248,  0.85848 , -0.52203 , -0.38122 , -0.43335 ,
       -0.73706 , -0.51609 , -0.13884 ,  0.65128 ,  0.66747 , -2.1334  ,
        0.93429 ,  0.24036 , -0.43398 ,  0.86494 , -0.78319 , -0.032875,
       -0.19761 , -0.23146 , -0.20256 ,  0.1193  ], dtype=float32)

In [ ]:
wiki_model.most_similar(positive=['king', 'woman'], negative=['man'], topn=5)

[('queen', 0.7698541283607483),
 ('monarch', 0.6843380928039551),
 ('throne', 0.6755735874176025),
 ('daughter', 0.6594556570053101),
 ('princess', 0.6520534753799438)]

In [ ]:
wiki_model.most_similar(positive=['france', 'london'], negative=['paris'], topn=5)

[('britain', 0.8921419978141785),
 ('england', 0.8002905249595642),
 ('australia', 0.7940487861633301),
 ('scotland', 0.7838967442512512),
 ('british', 0.7608305215835571)]

# Exercise 2: Embeddings with multiword ngrams

---

**Training Word2vec on a dataset**:
- Train a bigram detector using gensim.
- Train a Word2Vec model on the presidents' speeches. You must pass to Word2Vec a list of lists of bigram tokens (a list of tokenized sentences).
- Find the words most similar to, e.g. "united_states", "american_people" or others.
- Try both word2vec architectures.

**Have you seen the sparsity problem?**

In [ ]:
from gensim.models import Phrases

bigram_generator = Phrases(data.tokens)

In [ ]:
bigram_tokens = bigram_generator[data.tokens]

/usr/local/lib/python3.7/dist-packages/gensim/models/phrases.py:598: UserWarning: For a faster implementation, use the gensim.models.phrases.Phraser class
  warnings.warn("For a faster implementation, use the gensim.models.phrases.Phraser class")

In [ ]:
# use bigram_tokens as your new corpus (same code as before!)
model = Word2Vec(sentences=bigram_tokens, size=100, window=5, sg=1, seed=42)

In [ ]:
print(model.wv.most_similar('united_states', topn=10))

[('constitution', 0.9667254090309143), ('states', 0.9621188044548035), ('whole', 0.9528996348381042), ('rights', 0.9472708106040955), ('powers', 0.9415111541748047), ('executive', 0.9414318799972534), ('laws', 0.9409316778182983), ('general_government', 0.9398400187492371), ('interests', 0.9381714463233948), ('union', 0.9362156391143799)]

In [ ]:
print(model.wv.most_similar('american_people', topn=10))

[('second', 0.9975712299346924), ('destinies', 0.9974365234375), ('encouragement', 0.9973673224449158), ('officer', 0.9972285032272339), ('assume', 0.9971164464950562), ('expressed', 0.9969063401222229), ('same', 0.9968450665473938), ('source', 0.9966413974761963), ('direction', 0.9964177012443542), ('lot', 0.996334433555603)]

# Exercise 3

You can represent a document as the weighted sum of the word embeddings of the terms it contains, where the term weights are given by, e.g. Tf-Idf.

- Compute the document embeddings for the US presidential speeches corpus.
- Write a function that, given a document (speech) id, finds the top n most similar documents (adapt the previous one for most similar terms).


Hints (but there may be other / better solutions):

- To obtain the TfIdf values from the 'tfidf' matrix returned by fit_transform, use 'tfidf[doc_id, term_index]'. The list of terms (features) is returned by 'vectorizer.get_feature_names_out()'
- To obtain the Word2Vec embedding for a word, use 'model.wv[word]', where 'model = Word2Vec(...)'
- To obtain the document embedding, iterate over all of its words (that are present both as features for the TfIdf vectorizer and in the Word2Vec model vocabulary), and sum over all the products: (model.wv[word] * tfidf[doc_id, word_index])

In [ ]:
# Your code here

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
docs_tfidf = vectorizer.fit_transform(data.preprocessed)

model = Word2Vec(sentences=corpus, window=5, sg=1, seed=42) # we use skipgram

In [ ]:
tf_idf_names = vectorizer.get_feature_names_out()

In [ ]:
skip_gram_words = model.wv.vocab

In [ ]:
tfidf_feature_to_index = {word: i for i, word in enumerate(tf_idf_names)}

def tfidf_weight(doc_id, term):
    return docs_tfidf[doc_id, tfidf_feature_to_index[term]]

In [ ]:
skip_gram_set = set(skip_gram_words)
tfidf_set = set(tf_idf_names)

common_terms = skip_gram_set.intersection(tfidf_set)

In [ ]:
def get_document_embedding(doc_id, common_terms):
    document = data.tokens[doc_id]
    embedding = np.zeros_like(model.vector_size)
    for word in document:
        if word in common_terms:
            embedding = embedding + model.wv[word] * tfidf_weight(doc_id, word)

    return embedding

In [ ]:
doc_embeddings = np.zeros((data.shape[0], model.vector_size))

for i in range(data.shape[0]):
    doc_embeddings[i] = get_document_embedding(i, common_terms)

In [ ]:
doc_embeddings.shape

(56, 100)

In [ ]:
doc_cos = cosine_similarity(doc_embeddings, doc_embeddings)

def top_n_most_similar_document(doc_id, doc_sim, top_n=5):
    current_doc_sim = doc_sim[doc_id]
    return data[['president', 'year', 'text']].loc[(-current_doc_sim).argsort()[1:(top_n+1)]]

In [ ]:
doc_cos.shape

(56, 56)

In [ ]:
data.iloc[2,:].text

'Fellow citizens, without solicitation on my part, I have been chosen by the free and voluntary suffrages of my countrymen to the most honorable and most responsible office on earth. I am deeply impressed with gratitude for the confidence reposed in me. Honored with this distinguished consideration at an earlier period of life than any of my predecessors, I can not disguise the diffidence with which I am about to enter on the discharge of my official duties.\n\nIf the more aged and experienced men who have filled the office of President of the United States even in the infancy of the Republic distrusted their ability to discharge the duties of that exalted station, what ought not to be the apprehensions of one so much younger and less endowed now that our domain extends from ocean to ocean, that our people have so greatly increased in numbers, and at a time when so great diversity of opinion prevails in regard to the principles and policy which should characterize the administration of our Government? Well may the boldest fear and the wisest tremble when incurring responsibilities on which may depend our country\'s peace and prosperity, and in some degree the hopes and happiness of the whole human family.\n\nIn assuming responsibilities so vast I fervently invoke the aid of that Almighty Ruler of the Universe in whose hands are the destinies of nations and of men to guard this Heaven-favored land against the mischiefs which without His guidance might arise from an unwise public policy. With a firm reliance upon the wisdom of Omnipotence to sustain and direct me in the path of duty which I am appointed to pursue, I stand in the presence of this assembled multitude of my countrymen to take upon myself the solemn obligation "to the best of my ability to preserve, protect, and defend the Constitution of the United States."\n\nA concise enumeration of the principles which will guide me in the administrative policy of the Government is not only in accordance with the examples set me by all my predecessors, but is eminently befitting the occasion.\n\nThe Constitution itself, plainly written as it is, the safeguard of our federative compact, the offspring of concession and compromise, binding together in the bonds of peace and union this great and increasing family of free and independent States, will be the chart by which I shall be directed.\n\nIt will be my first care to administer the Government in the true spirit of that instrument, and to assume no powers not expressly granted or clearly implied in its terms. The Government of the United States is one of delegated and limited powers, arid it is by a strict adherence to the clearly granted powers and by abstaining from the exercise of doubtful or unauthorized implied powers that we have the only sure guaranty against the recurrence of those unfortunate collisions between the Federal and State authorities which have occasionally so much disturbed the harmony of our system and even threatened the perpetuity of our glorious Union.\n\n"To the States, respectively, or to the people" have been reserved "the powers not delegated to the United States by the Constitution nor prohibited by it to the States." Each State is a complete sovereignty within the sphere of its reserved powers. The Government of the Union, acting within the sphere of its delegated authority, is also a complete sovereignty. While the General Government should abstain from the exercise of authority not clearly delegated to it, the States should be equally careful that in the maintenance of their rights they do not overstep the limits of powers reserved to them. One of the most distinguished of my predecessors attached deserved importance to "the support of the State governments in all their rights, as the most competent administration for our domestic concerns and the surest bulwark against antirepublican tendencies," and to the "preservation of the General Government in its whole constitutional vigor, as the sheet anchor of our peace at home and safety abroad."\n\nTo the Government of the United States has been intrusted the exclusive management of our foreign affairs. Beyond that it wields a few general enumerated powers. It does not force reform on the States. It leaves individuals, over whom it casts its protecting influence, entirely free to improve their own condition by the legitimate exercise of all their mental and physical powers. It is a common protector of each and all the States; of every man who lives upon our soil, whether of native or foreign birth; of every religious sect, in their worship of the Almighty according to the dictates of their own conscience; of every shade of opinion, and the most free inquiry; of every art, trade, and occupation consistent with the laws of the States. And we rejoice in the general happiness, prosperity, and advancement of our country, which have been the offspring of freedom, and not of power.\n\nThis most admirable and wisest system of well-regulated self-government among men ever devised by human minds has been tested by its successful operation for more than half a century, and if preserved from the usurpations of the Federal Government on the one hand and the exercise by the States of powers not reserved to them on the other, will, I fervently hope and believe, endure for ages to come and dispense the blessings of civil and religious liberty to distant generations. To effect objects so dear to every patriot I shall devote myself with anxious solicitude. It will be my desire to guard against that most fruitful source of danger to the harmonious action of our system which consists in substituting the mere discretion and caprice of the Executive or of majorities in the legislative department of the Government for powers which have been withheld from the Federal Government by the Constitution. By the theory of our Government majorities rule, but this right is not an arbitrary or unlimited one. It is a right to be exercised in subordination to the Constitution and in conformity to it. One great object of the Constitution was to restrain majorities from oppressing minorities or encroaching upon their just rights. Minorities have a right to appeal to the Constitution as a shield against such oppression.\n\nThat the blessings of liberty which our Constitution secures may be enjoyed alike by minorities and majorities, the Executive has been wisely invested with a qualified veto upon the acts of the Legislature. It is a negative power, and is conservative in its character. It arrests for the time hasty, inconsiderate, or unconstitutional legislation, invites reconsideration, and transfers questions at issue between the legislative and executive departments to the tribunal of the people. Like all other powers, it is subject to be abused. When judiciously and properly exercised, the Constitution itself may be saved from infraction and the rights of all preserved and protected.\n\nThe inestimable value of our Federal Union is felt and acknowledged by all. By this system of united and confederated States our people are permitted collectively arid individually to seek their own happiness in their own way, and the consequences have been most auspicious. Since the Union was formed the number of the States has increased from thirteen to twenty-eight; two of these have taken their position as members of the Confederacy within the last week. Our population has increased from three to twenty millions. New communities and States are seeking protection under its aegis, and multitudes from the Old World are flocking to our shores to participate in its blessings. Beneath its benign sway peace and prosperity prevail. Freed from the burdens and miseries of war, our trade and intercourse have extended throughout the world. Mind, no longer tasked in devising means to accomplish or resist schemes of ambition, usurpation, or conquest, is devoting itself to man\'s true interests in developing his faculties and powers and the capacity of nature to minister to his enjoyments. Genius is free to announce its inventions and discoveries, and the hand is free to accomplish whatever the head conceives not incompatible with the rights of a fellow-being. All distinctions of birth or of rank have been abolished. All citizens, whether native or adopted, are placed upon terms of precise equality. All are entitled to equal rights and equal protection. No union exists between church and state, and perfect freedom of opinion is guaranteed to all sects and creeds.\n\nThese are some of the blessings secured to our happy land by our Federal Union. To perpetuate them it is our sacred duty to preserve it. Who shall assign limits to the achievements of free minds and free hands under the protection of this glorious Union? No treason to mankind since the organization of society would be equal in atrocity to that of him who would lift his hand to destroy it. He would overthrow the noblest structure of human wisdom, which protects himself and his fellow-man. He would stop the progress of free government and involve his country either in anarchy or despotism. He would extinguish the fire of liberty, which warms and animates the hearts of happy millions and invites all the nations of the earth to imitate our example. If he say that error and wrong are committed in the administration of the Government, let him remember that nothing human can be perfect, and that under no other system of government revealed by Heaven or devised by man has reason been allowed so free and broad a scope to combat error. Has the sword of despots proved to be a safer or surer instrument of reform in government than enlightened reason? Does he expect to find among the ruins of this Union a happier abode for our swarming millions than they now have under it? Every lover of his country must shudder at the thought of the possibility of its dissolution, and will be ready to adopt the patriotic sentiment, "Our Federal Union -- it must be preserved." To preserve it the compromises which alone enabled our fathers to form a common constitution for the government and protection of so many States and distinct communities, of such diversified habits, interests, and domestic institutions, must be sacredly and religiously observed. Any attempt to disturb or destroy these compromises, being terms of the compact of union, can lead to none other than the most ruinous and disastrous consequences.\n\nIt is a source of deep regret that in some sections of our country misguided persons have occasionally indulged in schemes and agitations whose object is the destruction of domestic institutions existing in other sections -- institutions which existed at the adoption of the Constitution and were recognized and protected by it. All must see that if it were possible for them to be successful in attaining their object the dissolution of the Union and the consequent destruction of our happy form of government must speedily follow.\n\nI am happy to believe that at every period of our existence as a nation there has existed, and continues to exist, among the great mass of our people a devotion to the Union of the States which will shield and protect it against the moral treason of any who would seriously contemplate its destruction. To secure a continuance of that devotion the compromises of the Constitution must not only be preserved, but sectional jealousies and heartburnings must be discountenanced, and all should remember that they are members of the same political family, having a common destiny. To increase the attachment of our people to the Union, our laws should be just. Any policy which shall tend to favor monopolies or the peculiar interests of sections or classes must operate to the prejudice of the interest of their fellow citizens, and should be avoided. If the compromises of the Constitution be preserved, if sectional jealousies and heartburnings be discountenanced, if our laws be just and the Government be practically administered strictly within the limits of power prescribed to it, we may discard all apprehensions for the safety of the Union.\n\nWith these views of the nature, character, and objects of the Government and the value of the Union, I shall steadily oppose the creation of those institutions and systems which in their nature tend to pervert it from its legitimate purposes and make it the instrument of sections, classes, and individuals. We need no national banks or other extraneous institutions planted around the Government to control or strengthen it in opposition to the will of its authors. Experience has taught us how unnecessary they are as auxiliaries of the public authorities -- how impotent for good and how powerful for mischief.\n\nOurs was intended to be a plain and frugal government, and I shall regard it to be my duty to recommend to Congress and, as far as the Executive is concerned, to enforce by all the means within my power the strictest economy in the expenditure of the public money which may be compatible with the public interests.\n\nA national debt has become almost an institution of European monarchies. It is viewed in some of them as an essential prop to existing governments. Melancholy is the condition of that people whose government can be sustained only by a system which periodically transfers large amounts from the labor of the many to the coffers of the few. Such a system is incompatible with the ends for which our republican Government was instituted. Under a wise policy the debts contracted in our Revolution and during the War of 1812 have been happily extinguished. By a judicious application of the revenues not required for other necessary purposes, it is not doubted that the debt which has grown out of the circumstances of the last few years may be speedily paid off.\n\nI congratulate my fellow citizens on the entire restoration of the credit of the General Government of the Union and that of many of the States. Happy would it be for the indebted States if they were freed from their liabilities, many of which were incautiously contracted. Although the Government of the Union is neither in a legal nor a moral sense bound for the debts of the States, and it would be a violation of our compact of union to assume them, yet we can not but feel a deep interest in seeing all the States meet their public liabilities and pay off their just debts at the earliest practicable period. That they will do so as soon as it can be done without imposing too heavy burdens on their citizens there is no reason to doubt. The sound moral and honorable feeling of the people of the indebted States can not be questioned, and we are happy to perceive a settled disposition on their part, as their ability returns after a season of unexampled pecuniary embarrassment, to pay off all just demands and to acquiesce in any reasonable measures to accomplish that object.\n\nOne of the difficulties which we have had to encounter in the practical administration of the Government consists in the adjustment of our revenue laws and the levy of the taxes necessary for the support of Government. In the general proposition that no more money shall be collected than the necessities of an economical administration shall require all parties seem to acquiesce. Nor does there seem to be any material difference of opinion as to the absence of right in the Government to tax one section of country, or one class of citizens, or one occupation, for the mere profit of another. "Justice and sound policy forbid the Federal Government to foster one branch of industry to the detriment of another, or to cherish the interests of one portion to the injury of another portion of our common country." I have heretofore declared to my fellow-citizens that "in my judgment it is the duty of the Government to extend, as far as it may be practicable to do so, by its revenue laws and all other means within its power, fair and just protection to all of the great interests of the whole Union, embracing agriculture, manufactures, the mechanic arts, commerce, and navigation." I have also declared my opinion to be "in favor of a tariff for revenue," and that "in adjusting the details of such a tariff I have sanctioned such moderate discriminating duties as would produce the amount of revenue needed and at the same time afford reasonable incidental protection to our home industry," and that I was "opposed to a tariff for protection merely, and not for revenue."\n\nThe power "to lay and collect taxes, duties, imposts, and excises" was an indispensable one to be conferred on the Federal Government, which without it would possess no means of providing for its own support. In executing this power by levying a tariff of duties for the support of Government, the raising of revenue should be the object and protection the incident. To reverse this principle and make protection the object and revenue the incident would be to inflict manifest injustice upon all other than the protected interests. In levying duties for revenue it is doubtless proper to make such discriminations within the revenue principle as will afford incidental protection to our home interests. Within the revenue limit there is a discretion to discriminate; beyond that limit the rightful exercise of the power is not conceded. The incidental protection afforded to our home interests by discriminations within the revenue range it is believed will be ample. In making discriminations all our home interests should as far as practicable be equally protected. The largest portion of our people are agriculturists. Others are employed in manufactures, commerce, navigation, and the mechanic arts. They are all engaged in their respective pursuits and their joint labors constitute the national or home industry. To tax one branch of this home industry for the benefit of another would be unjust. No one of these interests can rightfully claim an advantage over the others, or to be enriched by impoverishing the others. All are equally entitled to the fostering care and protection of the Government. In exercising a sound discretion in levying discriminating duties within the limit prescribed, care should be taken that it be done in a manner not to benefit the wealthy few at the expense of the toiling millions by taxing lowest the luxuries of life, or articles of superior quality and high price, which can only be consumed by the wealthy, and highest the necessaries of life, or articles of coarse quality and low price, which the poor and great mass of our people must consume. The burdens of government should as far as practicable be distributed justly and equally among all classes of our population. These general views, long entertained on this subject, I have deemed it proper to reiterate. It is a subject upon which conflicting interests of sections and occupations are supposed to exist, and a spirit of mutual concession and compromise in adjusting its details should be cherished by every part of our widespread country as the only means of preserving harmony and a cheerful acquiescence of all in the operation of our revenue laws. Our patriotic citizens in every part of the Union will readily submit to the payment of such taxes as shall be needed for the support of their Government, whether in peace or in war, if they are so levied as to distribute the burdens as equally as possible among them.\n\nThe Republic of Texas has made known her desire to come into our Union, to form a part of our Confederacy and enjoy with us the blessings of liberty secured and guaranteed by our Constitution. Texas was once a part of our country -- was unwisely ceded away to a foreign power -- is now independent, and possesses an undoubted right to dispose of a part or the whole of her territory and to merge her sovereignty as a separate and independent state in ours. I congratulate my country that by an act of the late Congress of the United States the assent of 

In [ ]:
top_n_most_similar_document(2, doc_cos, 5)

   president  year  \
5   Jackson   1833
1   Harrison  1889
47  Taft      1909
49  McKinley  1897
41  Hayes     1877


# Exercise 4

Use Doc2Vec (https://radimrehurek.com/gensim/models/doc2vec.html) to compute the embeddings for the documents in the presidential speeches dataset. Write a function that finds the most similar documents for a given document(adapt the previous function).

In [ ]:
# Your code here

from gensim.models.doc2vec import Doc2Vec, TaggedDocument

In [ ]:
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(data.tokens)]

In [ ]:
doc_model = Doc2Vec(documents, window=5, seed=42)

In [ ]:
# generic method to get an emebedding not based only on the document id
# d2v_doc_embeddings = np.array([doc_model.infer_vector(data.tokens[i]) for i in range(data.shape[0])])


# use the static embedding generated by doc2vec model
d2v_doc_embeddings = np.array([doc_model.docvecs[i] for i in range(data.shape[0])])

In [ ]:
d2v_doc_embeddings.shape

(56, 100)

In [ ]:
d2v_doc_cos = cosine_similarity(d2v_doc_embeddings, d2v_doc_embeddings)

In [ ]:
def top_n_most_similar_document(doc_id, doc_sim, top_n=5):
    current_doc_sim = doc_sim[doc_id]
    return data[['president', 'year', 'text']].loc[(-current_doc_sim).argsort()[1:(top_n+1)]]

In [ ]:
top_n_most_similar_document(2, d2v_doc_cos)

    president  year  \
43  Madison    1809
31  Hayes      1877
22  Adams      1797
54  Monroe     1817
46  Cleveland  1885


In [ ]:
ex_query = 'fellow citizien of the united states of america'
# infer the query (or a doc) vector using only the words (so good for new documents or queries)
q = doc_model.infer_vector(ex_query)

# print(cosine_similarity(d2v_doc_embeddings, q.reshape(1, -1)))
cosine_similarity(d2v_doc_embeddings, q.reshape(1, -1)).shape

(56, 1)

In [ ]:

def get_top_n_from_query(query, doc_embeddings, top_n=5):
    similarities = cosine_similarity(doc_embeddings, q.reshape(1, -1))
    # enumerate to get doc_number: similarity measure and sort accoring to the similarity
    sorted_index_list = sorted(enumerate(similarities), key=lambda item: item[1], reverse=True)
    return sorted_index_list[:top_n]

get_top_n_from_query(q, d2v_doc_embeddings)

[(0, array([0.9814495], dtype=float32)),
 (37, array([0.98106486], dtype=float32)),
 (40, array([0.9809127], dtype=float32)),
 (42, array([0.980842], dtype=float32)),
 (3, array([0.9804632], dtype=float32))]

In [ ]:
ex_query

'fellow citizien of the united states of america'

In [ ]:
print(data.iloc[3].preprocessed)

my fellow citizens  today we celebrate the mystery of american renewal  this ceremony is held in the depth of winter  but by the words we speak and the faces we show the world  we force the spring  a spring reborn in the world s oldest democracy  that brings forth the vision and courage to reinvent america  when our founders boldly declared america s independence to the world  and our purposes to the almighty  they knew that america  to endure  would have to change  not change for change sake  but change to preserve america s ideals  life  liberty  the pursuit of happiness

though we march to the music of our time  our mission is timeless  each generation of american s must define what it means to be an american  on behalf of our nation  i salute my predecessor  president bush  for his half century of service to america and i thank the millions of men and women whose steadfastness and sacrifice triumphed over depression  fascism and communism

today  a generation raised in the shadows of the cold war assumes new responsibilities in a world warmed by the sunshine of freedom  but threatened still by ancient hatreds and new plagues  raised in unrivalled prosperity  we inherit an economy that is still the world s strongest  but is weakened by business failures  stagnant wages  increasing inequality  and deep divisions among our own people

when george washington first took the oath i have just sworn to uphold  news travelled slowly across the land by horseback  and across the ocean by boat  now the sights and sounds of this ceremony are broadcast instantaneously tobillions around the world  communications and commerce are global  investment is mobile  technology is almost magical  and ambition for a better life is now universal

we earn our livelihood in america today in peaceful competition with people all across the earth  profound and powerful forces are shaking and remaking our world  and the urgent question of our time is whether we can make change our friend and not our enemy  this new world has already enriched the lives of millions of americans who are able to compete and win in it  but when most people are working harder for less  when others cannot work at all  when the cost of health care devastates families and threatens to bankrupt our enterprises  great and small  when the fear of crime robs law abiding citizens of their freedom  and when millions of poor children cannot even imagine the lives we are calling them to lead  we have not made change our friend

we know we have to face hard truths and take strong steps  but we have not done so  instead we have drifted  and that drifting has eroded our resources  fractured our economy  and shaken our confidence  though our challenges are fearsome  so are our strengths  americans have ever been a restless  questing  hopeful people  and we must bring to our task today the vision and will of those who came before us  from our revolution to the civil war  to the great depression  to the civil rights movement  our people have always mustered the determination to construct from these crises the pillars of our history  thomas jefferson believed that to preserve the very foundations of our nation we would need dramatic change from time to time  well  my fellow americans  this is our time  let us embrace it

our democracy must be not only the envy of the world but the engine of our own renewal  there is nothing wrong with america that cannot be cured by what is right with america

and so today we pledge an end to the era of deadlock and drift  and a new season of american renewal has begun

to renew america we must be bold  we must do what no generation has had to do before  we must invest more in our own people  in their jobs  and in their future  and at the same time cut our massive debt and we must do so in a world in which we must compete for every opportunity  it will not be easy  it will require sacrifice  but it can be done  and done fairly  not choosing sacrifice for its own sake  but for our own sake

we must provide for our nation the way a family provides for its children  our founders saw themselves in the light of posterity  we can do no less  anyone who has ever watched a child s eyes wander into sleep knows what posterity is  posterity is the world to come  the world for whom we hold our ideals  from whom we have borrowed our planet  and to whom we bear sacred responsibilities  we must do what america does best  offer more opportunity to all and demand more responsibility from all

it is time to break the bad habit of expecting something for nothing  from our government  or from each other  let us all take more responsibility  not only for ourselves and our families  but for our communities and our country  to renew america we must revitalize our democracy  this beautiful capitol  like every capitol since the dawn of civilization  is often a place of intrigue and calculation  powerful people maneuver for position and worry endlessly about who is in and who is out  who is up and who is down  forgetting those people whose toil and sweat sends us here and paves our way

americans deserve better  and in this city today there are people who want to do better  and so i say to all of you here  let us resolve to reform our politics  so that power and privilege no longer shout down the voice of the people  let us put aside personal advantage  so that we can feel the pain and see the promise of america  let us resolve to make our government a place for what franklin roosevelt called  bold  persistent experimentation  a government for our tomorrows  not our yesterdays   let us give this capitol back to the people to whom it belongs

to renew america we must meet challenges abroad  as well as at home  there is no longer a clear division between what is foreign and what is domestic  the world economy  the world environment  the world aids crisis  the world arms race  they affect us all  today as an old order passes  the new world is more free  but less stable  communism s collapse has called forth old animosities  and new dangers  clearly  america must continue to lead the world we did so much to make  while america rebuilds at home  we will not shrink from the challenges nor fail to seize the opportunities of this new world

together with our friends and allies  we will work together to shape change  lest it engulf us  when our vital interests are challenged  or the will and conscience of the international community is defied  we will act  with peaceful diplomacy whenever possible  with force when necessary  the brave americans serving our nation today in the persian gulf  in somalia  and wherever else they stand  are testament to our resolve  but our greatest strength is the power of our ideas  which are still new in many lands  across the world  we see them embraced and we rejoice  our hopes  our hearts  our hands  are with those on every continent  who are building democracy and freedom  their cause is america s cause  the american people have summoned the change we celebrate today  you have raised your voices in an unmistakable chorus  you have cast your votes in historic numbers  you have changed the face of congress  the presidency  and the political process itself  yes  you  my fellow americans  have forced the spring  now we must do the work the season demands  to that work i now turn with all the authority of my office  i ask the congress to join with me  but no president  no congress  no government can undertake this mission alone

my fellow americans  you  too  must play your part in our renewal  i challenge a new generation of young americans to a season of service  to act on your idealism  by helping troubled children  keeping company with those in need  reconnecting our torn communities  there is so much to be done  enough  indeed  for millions of others who are still young in spirit  to give of themselves in service  too  in serving we recognize a simple  but powerful  truth  we need each other  and we must care for one another  today we do more than celebrate america  we rededicate ourselves to the very idea of america  an idea born in revolution  and renewed through two centuries of challenge  an idea tempered by the knowledge that but for fate  we  the fortunate and the unfortunate  might have been each other  an idea ennobled by the faith that our nation can summon from its myriad diversity  the deepest measure of unity  an idea infused with the conviction that america s journey long  heroic journey must go forever upward

and so  my fellow americans  as we stand at the edge of the st century  let us begin anew  with energy and hope  with faith and discipline  and let us work until our work is done  the scripture says   and let us not be weary in well doing  for in due season we shall reap  if we faint not   from this joyful mountaintop of celebration we hear a call to service in the valley  we have heard the trumpets  we have changed the guard  and now each in our own way  and with god s help  we must answer the call

thank you  and god bless you all