# 1st LAB: Document Representation

# Document Representation

Refers to the process of converting raw text or documents into a format that can be understood and processed by machine learning models or algorithms. Since machines can't directly work with raw text, we need to transform it into structured numerical representations that capture the underlying meaning and structure of the document.

### Create sample data

In [ ]:
import pandas as pd
import numpy as np

corpus = [
    'The sky is blue and beautiful.',
    'Love this blue and beautiful sky!',
    'The quick brown fox jumps over the lazy dog.',
    "A king's breakfast has sausages, ham, bacon, eggs, toast and beans",
    'I love green eggs, ham, sausages and bacon!',
    'The brown fox is quick and the blue dog is lazy!',
    'The sky is very blue and the sky is very beautiful today',
    'The dog is lazy but the brown fox is quick!'
]

labels = [
    'weather', 'weather', 'animals', 'food', 'food', 'animals', 'weather',
    'animals'
]

corpus = np.array(corpus)
corpus_df = pd.DataFrame({'Document': corpus, 'Category': labels})
corpus_df = corpus_df[['Document', 'Category']]
corpus_df

                                            Document Category
0                     The sky is blue and beautiful.  weather
1                  Love this blue and beautiful sky!  weather
2       The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, e...     food
4        I love green eggs, ham, sausages and bacon!     food
5   The brown fox is quick and the blue dog is lazy!  animals
6  The sky is very blue and the sky is very beaut...  weather
7        The dog is lazy but the brown fox is quick!  animals

### Binary vectorizer

A Binary Vectorizer is a technique used to represent text data in a binary format, where each feature (typically a word) is either present or absent in a document. The binary vectorization approach is a variation of the Bag of Words (BoW) model, but instead of counting the frequency of words, it only records whether a word appears or not.

### Count Vectorizer

The Count Vectorizer is one of the most widely used techniques for converting text documents into a structured numerical format. It is part of the Bag of Words (BoW) model, which represents text data by counting the occurrences of words in a document. In simpler terms, the Count Vectorizer creates a vector where each element corresponds to the frequency of a word in a document. This vector can then be used as input to machine learning models for tasks like text classification, sentiment analysis, and information retrieval.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(corpus_df.Document.iloc[:100]) #top 100 documents (not required here)
cv_matrix = cv_matrix.toarray()
print(cv_matrix)

[[1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 2 0 0 0 0]
 [1 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0]
 [1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0 1 0 1 0 0 0 2 0 0 1 0 0 1 0 0 2 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 2 0 0 1 2]
 [0 0 0 0 0 0 1 1 1 0 1 0 0 0 2 0 0 1 0 0 1 0 0 2 0 0 0 0]]

In [ ]:
# get all unique words in the corpus
vocab = cv.get_feature_names_out()

# show document feature vectors
pd.DataFrame(cv_matrix, columns=vocab)

,and,bacon,beans,beautiful,blue,breakfast,brown,but,dog,eggs,...,love,over,quick,sausages,sky,the,this,toast,today,very
0,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
1,1,0,0,1,1,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
2,0,0,0,0,0,0,1,0,1,0,...,0,1,1,0,0,2,0,0,0,0
3,1,1,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,0
5,1,0,0,0,1,0,1,0,1,0,...,0,0,1,0,0,2,0,0,0,0
6,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,2,2,0,0,1,2
7,0,0,0,0,0,0,1,1,1,0,...,0,0,1,0,0,2,0,0,0,0

###TF_IDF

TF-IDF (Term Frequency-Inverse Document Frequency) is a statistical measure used to evaluate the importance of a word within a document relative to a collection of documents (also called a corpus). It is commonly used in text mining, information retrieval, and natural language processing (NLP) to transform text into numerical features, which can then be used for machine learning tasks such as classification, clustering, or recommendation.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Setting the vectorizer
tv = TfidfVectorizer(min_df=0., max_df=1., use_idf=True)

# Transforming the data to vectors
tv_matrix = tv.fit_transform(corpus_df.Document)
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names_out()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

,and,bacon,beans,beautiful,blue,breakfast,brown,but,dog,eggs,...,love,over,quick,sausages,sky,the,this,toast,today,very
0,0.32,0.00,0.00,0.47,0.41,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.47,0.36,0.00,0.00,0.0,0.0
1,0.27,0.00,0.00,0.39,0.34,0.00,0.00,0.00,0.00,0.00,...,0.45,0.00,0.00,0.00,0.39,0.00,0.54,0.00,0.0,0.0
2,0.00,0.00,0.00,0.00,0.00,0.00,0.30,0.00,0.30,0.00,...,0.00,0.41,0.30,0.00,0.00,0.46,0.00,0.00,0.0,0.0
3,0.18,0.30,0.35,0.00,0.00,0.35,0.00,0.00,0.00,0.30,...,0.00,0.00,0.00,0.30,0.00,0.00,0.00,0.35,0.0,0.0
4,0.23,0.38,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.38,...,0.38,0.00,0.00,0.38,0.00,0.00,0.00,0.00,0.0,0.0
5,0.20,0.00,0.00,0.00,0.26,0.00,0.29,0.00,0.29,0.00,...,0.00,0.00,0.29,0.00,0.00,0.45,0.00,0.00,0.0,0.0
6,0.15,0.00,0.00,0.22,0.19,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.43,0.34,0.00,0.00,0.3,0.6
7,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.39,0.28,0.00,...,0.00,0.00,0.28,0.00,0.00,0.44,0.00,0.00,0.0,0.0

### Document Similarity

It refers to the task of measuring how similar two or more text documents are to each other based on their content. Document similarity is crucial in many NLP applications such as:

- Search Engines: Ranking documents based on relevance to a search query.

- Recommendation Systems: Suggesting similar documents or items.

- Plagiarism Detection: Identifying copied content.

- Text Clustering: Grouping similar documents together.

- Question Answering: Matching user queries to relevant documents.

The basic idea is to convert text documents into a mathematical representation and then apply a similarity measure to quantify how similar they are.

Cosine similarity is one of the most popular methods for measuring the similarity between two documents. It measures the cosine of the angle between two vectors in a multi-dimensional space. If the vectors are similar (i.e., the angle between them is small), the cosine similarity is close to 1; if they are completely different, the cosine similarity is 0.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tv_matrix)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

,0,1,2,3,4,5,6,7
0,1.000000,0.592497,0.167270,0.056604,0.073640,0.541928,0.704836,0.362454
1,0.592497,1.000000,0.000000,0.047703,0.236620,0.142703,0.360920,0.000000
2,0.167270,0.000000,1.000000,0.000000,0.000000,0.645455,0.155793,0.627881
3,0.056604,0.047703,0.000000,1.000000,0.493841,0.035512,0.026360,0.000000
4,0.073640,0.236620,0.000000,0.493841,1.000000,0.046201,0.034294,0.000000
5,0.541928,0.142703,0.645455,0.035512,0.046201,1.000000,0.425888,0.869431
6,0.704836,0.360920,0.155793,0.026360,0.034294,0.425888,1.000000,0.337583
7,0.362454,0.000000,0.627881,0.000000,0.000000,0.869431,0.337583,1.000000

# Document similarity to a query

In many applications, we are not just interested in comparing documents to each other but also in comparing a document (or a set of documents) to a query. A query is typically a user's input, which could be a search term, a sentence, or a question, and the goal is to find the document or documents that are most relevant to that query.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
docs_tfidf = vectorizer.fit_transform(corpus_df.Document)

def get_tf_idf_query_similarity(vectorizer, docs_tfidf, query):
    """
    vectorizer: TfIdfVectorizer model
    docs_tfidf: tfidf vectors for all docs
    query: query doc
    return: cosine similarity between query and all docs
    """
    query_tfidf = vectorizer.transform([query])

    similarity = cosine_similarity(query_tfidf, docs_tfidf).flatten()
    return similarity


display(get_tf_idf_query_similarity(vectorizer, docs_tfidf, 'eggs'))
display(get_tf_idf_query_similarity(vectorizer, docs_tfidf, 'king eggs'))
display(get_tf_idf_query_similarity(vectorizer, docs_tfidf, 'green eggs'))

corpus_df.head(10)

array([0.        , 0.        , 0.        , 0.29521487, 0.38406851,
       0.        , 0.        , 0.        ])

array([0.        , 0.        , 0.        , 0.45960141, 0.24669797,
       0.        , 0.        , 0.        ])

array([0.        , 0.        , 0.        , 0.18962478, 0.59793204,
       0.        , 0.        , 0.        ])

                                                             Document Category
0                                      The sky is blue and beautiful.  weather
1                                   Love this blue and beautiful sky!  weather
2                        The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, eggs, toast and beans     food
4                         I love green eggs, ham, sausages and bacon!     food
5                    The brown fox is quick and the blue dog is lazy!  animals
6            The sky is very blue and the sky is very beautiful today  weather
7                         The dog is lazy but the brown fox is quick!  animals

# Exercise 3

1. Write a function that uses TfidfVectorizer with binary tf values
2. Write a function that creates TF-IDF vector of n-grams (try to run using n=2 and n=3)
3. Write a function that vectorizes (e.g. TF-IDF) a query and a set of documents, and print the distance between the query and each document and sort them

> a. try to explore the BOW, TF-IDF, Count Vector \\
> b. try to compare different metrics [here is the list](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics.pairwise)

*Hint: For point 1. and 2. use the documenation of TfidfVectorizer sklearn!*

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def binary_tfidf(corpus):
    tfidf_vectorizer = TfidfVectorizer(min_df=0., max_df=1., binary=True)

    # EXERCISE: fit to the corpus
    docs_tfidf = tfidf_vectorizer.fit_transform(corpus)

    # get all unique words in the corpus
    vocab = tfidf_vectorizer.get_feature_names_out()

    # show document feature vectors
    tf_idf_df = pd.DataFrame(docs_tfidf.toarray(), columns=vocab)
    return tf_idf_df

def ngram_tfidf(corpus, n, m):
    tfidf_vectorizer = TfidfVectorizer(min_df=0., max_df=1., ngram_range=(n,m))

    # EXERCISE: fit to the corpus
    docs_tfidf = tfidf_vectorizer.fit_transform(corpus)

    # get all unique words in the corpus
    vocab = tfidf_vectorizer.get_feature_names_out()

    # show document feature vectors
    tf_idf_df = pd.DataFrame(docs_tfidf.toarray(), columns=vocab)
    return tf_idf_df

binary_docs = binary_tfidf(corpus_df.Document)
bigram_docs = ngram_tfidf(corpus_df.Document, 2, 2)
trigram_docs = ngram_tfidf(corpus_df.Document, 3, 3)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

def get_tf_idf_query_similarity(corpus, query):

    vectorizer = CountVectorizer() # just change this for the other methods

    # EXERCISE: fit to the corpus
    docs_tfidf = vectorizer.fit_transform(corpus)
    query_tfidf = vectorizer.transform([query])

    # EXERCISE: Apply euclidean distances between query_tfidf, docs_tfidf
    # and then flatten
    distances = euclidean_distances(query_tfidf, docs_tfidf).flatten()
    return distances

display(get_tf_idf_query_similarity(corpus_df.Document, 'eggs'))
display(get_tf_idf_query_similarity(corpus_df.Document, 'king eggs'))
display(get_tf_idf_query_similarity(corpus_df.Document, 'green eggs'))

corpus_df.head(10)

array([2.64575131, 2.64575131, 3.46410162, 3.        , 2.44948974,
       4.        , 4.58257569, 3.87298335])

array([2.82842712, 2.82842712, 3.60555128, 2.82842712, 2.64575131,
       4.12310563, 4.69041576, 4.        ])

array([2.82842712, 2.82842712, 3.60555128, 3.16227766, 2.23606798,
       4.12310563, 4.69041576, 4.        ])

                                                             Document Category
0                                      The sky is blue and beautiful.  weather
1                                   Love this blue and beautiful sky!  weather
2                        The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, eggs, toast and beans     food
4                         I love green eggs, ham, sausages and bacon!     food
5                    The brown fox is quick and the blue dog is lazy!  animals
6            The sky is very blue and the sky is very beautiful today  weather
7                         The dog is lazy but the brown fox is quick!  animals